export const GET_ASSET_REQUEST = "GET_ASSET_REQUEST"
export const GET_ASSET_SUCCESS = "GET_ASSET_SUCCESS"
export const GET_ASSET_FAILURE = "GET_ASSET_FAILURE"

export const GET_USER_ASSETS_REQUEST = "GET_USER_ASSETS_REQUEST"
export const GET_USER_ASSETS_SUCCESS = "GET_USER_ASSETS_SUCCESS"
export const GET_USER_ASSETS_FAILURE = "GET_USER_ASSETS_FAILURE"

export const GET_ALL_ASSETS_REQUEST = "GET_ALL_ASSETS_REQUEST"
export const GET_ALL_ASSETS_SUCCESS = "GET_ALL_ASSETS_SUCCESS"
export const GET_ALL_ASSETS_FAILURE = "GET_ALL_ASSETS_FAILURE"
